import { Inter } from "next/font/google";
import "./globals.css";

import Footer from "@/components/Footer";
import Header from "@/components/Header";

// const inter = Inter({ subsets: ["latin"] });
import { comfortaa, space_mono } from "$/fonts/fonts";
import clsx from "clsx";
import LinkAnimated from "@/components/LinkAnimated";

export const metadata = {
  title: "Brain.exe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={clsx(space_mono.variable, comfortaa.variable)}>
      <body>
        <Header />
        <LinkAnimated/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
