import "./globals.css";

import Footer from "@/components/Footer";
import Header from "@/components/Header";

import { be_vietname_pro, comfortaa, josefin_slab, space_mono } from "@/app/fonts";
import clsx from "clsx";
import LinkAnimated from "@/components/LinkAnimated";
import Root from "./Root";
import Separator from "@/components/Separator";
import Container from "@/components/Container";
import BlockSeparator from "@/components/BlockSeparator";

export const metadata = {
    title: "Brain.exe",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <Root
            lang='en'
            className={clsx(space_mono.variable, be_vietname_pro.variable, josefin_slab.variable)}>
            <body>
                <div id='root'>
                    <div className='column'></div>
                    <div className='column'></div>
                    <div className='column'></div>
                    <Header />
                    <BlockSeparator preset={5} />
                    {children}
                </div>
            </body>
        </Root>
    );
}
